/**
 * Structural pool balance derivations.
 *
 * All balances derive from `revenue_splits` — there is no separate
 * "pool ledger" table. The RevenueSplit rows ARE the ledger; the
 * pools are just filtered aggregations over them.
 *
 * Read-only. Never mutates. Use `settlement-splits.ts` to actually
 * write inflows.
 */
import { MOCK_SPLITS } from "@/lib/mock-data/splits";
import { MOCK_BUILD_VOUCHERS } from "@/lib/mock-data/vouchers";
import {
  HOUSE_LP_ID,
  HOUSE_TREASURY_ID,
} from "@/lib/settlement-splits";
import type { RevenueSplit, RevenueSplitSourceKind } from "@/lib/types";

/** Total dollars sitting in Treasury (sum across every settlement kind). */
export function treasuryBalance(): number {
  return MOCK_SPLITS.filter(
    (s) => s.recipientId === HOUSE_TREASURY_ID && s.pool === "reserve",
  ).reduce((sum, s) => sum + Number(s.amount), 0);
}

/** Total dollars sitting in the Liquidity Pool. */
export function liquidityPoolBalance(): number {
  return MOCK_SPLITS.filter(
    (s) => s.recipientId === HOUSE_LP_ID && s.pool === "reserve",
  ).reduce((sum, s) => sum + Number(s.amount), 0);
}

/** Total dollars distributed through the admin pool over all time. */
export function adminPoolLifetimeTotal(): number {
  return MOCK_SPLITS.filter((s) => s.pool === "admin").reduce(
    (sum, s) => sum + Number(s.amount),
    0,
  );
}

/** Total dollars distributed through the contributor pool over all time. */
export function contributorPoolLifetimeTotal(): number {
  return MOCK_SPLITS.filter((s) => s.pool === "contributor").reduce(
    (sum, s) => sum + Number(s.amount),
    0,
  );
}

/** Per-admin lifetime earnings from the admin pool. */
export function adminEarningsByUser(): Map<string, number> {
  const byUser = new Map<string, number>();
  for (const s of MOCK_SPLITS) {
    if (s.pool !== "admin") continue;
    byUser.set(s.recipientId, (byUser.get(s.recipientId) ?? 0) + Number(s.amount));
  }
  return byUser;
}

export interface PoolInflow {
  splitId: string;
  amount: number;
  sourceKind: RevenueSplitSourceKind;
  sourceId: string;
  at: string;
  notes: string | null;
}

/**
 * Inflow history for a given structural pool recipient (Treasury or
 * LP). Freshest first. Powers the admin pool surface.
 */
export function inflowHistory(recipientId: string, limit = 50): PoolInflow[] {
  return MOCK_SPLITS.filter((s) => s.recipientId === recipientId)
    .map((s) => ({
      splitId: s.id,
      amount: Number(s.amount),
      sourceKind: s.sourceKind,
      sourceId: s.sourceId,
      at: s.decidedAt ?? s.payoutSentAt ?? "",
      notes: s.notes,
    }))
    .sort((a, b) => b.at.localeCompare(a.at))
    .slice(0, limit);
}

/**
 * All revenue-split rows for a given source event (e.g., every row
 * generated by contract p_004 settling, or by whitelist_purchase
 * wlp_001 completing).
 */
export function splitsForSource(sourceId: string): RevenueSplit[] {
  return MOCK_SPLITS.filter((s) => s.sourceId === sourceId).sort((a, b) =>
    (a.decidedAt ?? "").localeCompare(b.decidedAt ?? ""),
  );
}

// ────────────────────────────────────────────────────────────────
//  $BUILD-side pool balances (Treasury + LP sentinel holdings)
// ────────────────────────────────────────────────────────────────

function sumVouchersForSentinel(sentinelId: string): number {
  return MOCK_BUILD_VOUCHERS.filter(
    (v) => v.userId === sentinelId && v.swapStatus !== "forfeited",
  ).reduce((sum, v) => sum + Number(v.amount), 0);
}

/** Total $BUILD sitting in the Treasury sentinel wallet. */
export function treasuryBuildBalance(): number {
  return sumVouchersForSentinel(HOUSE_TREASURY_ID);
}

/** Total $BUILD sitting in the LP sentinel wallet. */
export function liquidityPoolBuildBalance(): number {
  return sumVouchersForSentinel(HOUSE_LP_ID);
}
